# Generated by Django 2.2.4 on 2019-08-11 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0003_touristspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristspot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='attractions',
            field=models.ManyToManyField(blank=True, null=True, to='attractions.Attraction'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
