# Generated by Django 2.2.4 on 2019-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190811_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attraction'),
        ),
    ]
