# Generated by Django 2.2.4 on 2019-08-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_touristspot_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
        ),
    ]
