# Generated by Django 2.2.4 on 2019-08-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190811_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='review',
            name='review_points',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
            preserve_default=False,
        ),
    ]
