# Generated by Django 2.2.4 on 2019-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('minimum_age', models.IntegerField()),
            ],
        ),
    ]
