# Generated by Django 2.2.4 on 2019-08-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20190811_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
